# Generated by Django 5.1.3 on 2024-11-20 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0004_alter_categoriascuentasmodel_tipo_categoria'),
        ('cuentas', '0002_alter_cuentasmodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('GASTO', 'Gasto'), ('INGRESO', 'Ingreso'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], default='GASTO', max_length=15, verbose_name='Tipo de transaccion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la transaccion')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion de la transaccion')),
                ('fecha_movimiento', models.DateField(verbose_name='Fecha de la transaccion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoriascuentasmodel')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuentasmodel')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion_transacciones', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion_transacciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
