# Generated by Django 5.1.3 on 2024-11-30 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC de la empresa')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numero', models.IntegerField(verbose_name='Número exterior')),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la sucursal')),
                ('telefono', models.CharField(max_length=15, verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numero', models.IntegerField(verbose_name='Número exterior')),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
