# Generated by Django 5.1.3 on 2024-12-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='colonia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='colonia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
    ]
