# Generated by Django 5.1.3 on 2024-11-19 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la cuenta')),
                ('tipo_cuenta', models.CharField(choices=[('Ahorro', 'Ahorro'), ('Inversion', 'Inversion'), ('Nomina', 'Nomina'), ('Efectivo', 'Efectivo'), ('Debito', 'Debito'), ('Credito', 'Credito')], max_length=100, verbose_name='Tipo de cuenta')),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo inicial')),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo actual')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion_cuentas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion_cuentas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
