# Generated by Django 5.1.3 on 2024-11-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriascuentasmodel',
            name='tipo_categoria',
            field=models.CharField(choices=[('GASTO', 'Gasto'), ('INGRESO', 'Ingreso'), ('AHORRO', 'Ahorro'), ('DEUDA', 'Deuda'), ('OTRO', 'Otro')], default='INGRESO', max_length=10, verbose_name='Tipo de categoria'),
        ),
    ]
