# Generated by Django 5.1.3 on 2024-11-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoriascuentasmodel_tipo_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriascuentasmodel',
            options={'verbose_name': 'Categoria de cuenta', 'verbose_name_plural': 'Categorias de cuentas'},
        ),
        migrations.AlterField(
            model_name='categoriascuentasmodel',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion de la categoria'),
        ),
    ]
