# Generated by Django 5.1.3 on 2024-11-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_categoriascuentasmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriascuentasmodel',
            name='tipo_categoria',
            field=models.CharField(choices=[('GASTO', 'Gasto'), ('INGRESO', 'Ingreso'), ('AHORRO', 'Ahorro'), ('DEUDA', 'Deuda'), ('OTRO', 'Otro')], default='GASTO', max_length=10, verbose_name='Tipo de categoria'),
        ),
    ]
