# Generated by Django 5.1.3 on 2024-12-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_sucursal_email_alter_sucursal_telefono'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del contrato')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Diario')),
                ('tipo', models.CharField(choices=[('I', 'Indefinido'), ('D', 'Definido'), ('P', 'Por proyecto'), ('H', 'Por horas'), ('T', 'Temporal'), ('O', 'Otro')], max_length=1, verbose_name='Tipo de contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del puesto')),
                ('descripcion', models.TextField(verbose_name='Descripción del puesto')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.contrato', verbose_name='Contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.persona', verbose_name='Persona')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal', verbose_name='Sucursal')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.puesto', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.contrato', verbose_name='Contrato')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la incidencia')),
                ('descripcion', models.TextField(verbose_name='Descripción de la incidencia')),
                ('clasificacion', models.CharField(choices=[('J', 'Justificada'), ('I', 'Injustificada'), ('P', 'Permiso'), ('V', 'Vacaciones'), ('O', 'Otro')], max_length=1, verbose_name='Clasificación de la incidencia')),
                ('estado', models.CharField(choices=[('A', 'Aceptada'), ('R', 'Rechazada'), ('P', 'Pendiente')], default='P', max_length=1, verbose_name='Estado de la incidencia')),
                ('tipo', models.CharField(choices=[('D', 'Deducción'), ('A', 'Bono'), ('O', 'Otro')], max_length=1, verbose_name='Tipo de incidencia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.gerente', verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la entrevista')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios de la entrevista')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado de solicitud')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.persona', verbose_name='Persona')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal', verbose_name='Sucursal')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.puesto', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
            },
        ),
    ]
