# Generated by Django 5.1.3 on 2024-12-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_contrato_puesto_empleado_gerente_incidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la nómina')),
                ('bonos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonos')),
                ('deducciones', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deducciones')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de la nómina')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
            },
        ),
    ]
