# Generated by Django 5.1.3 on 2024-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='clave',
            field=models.IntegerField(default=0, unique=True, verbose_name='Clave de empleado'),
        ),
    ]
